course/urls.py
from django.urls import path, re_path
from .views import CourseListView, CourseDetailView, CourseInfoView, VideoPlayView

app_name = 'course'

urlpatterns = [
    path('list/', CourseListView.as_view(), name='course_list'),
    re_path('detail/(?P<course_id>\d+)/', CourseDetailView.as_view(), name='course_detail'),
    re_path('info/(?P<course_id>\d+)/', CourseInfoView.as_view(), name='course_info'),
    re_path('video/(?P<video_id>\d+)/', VideoPlayView.as_view(), name="video_play"),
]

studyonline/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.views.static import serve
from studyonline.settings import MEDIA_ROOT
# from users.views import LoginView, RegisterView, ActiveUserView,ForgetPwdView, ResetView,ModifyPwdView
# from users.views import IndexView, login, signup, logout, change_password, ProfView
from users.views import IndexView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    # path('login/', login.as_view(), name='login'),
    # path('logout/', logout.as_view(), name='logout'),
    # path('signup/', signup.as_view(), name='signup'),
    # path('captcha/', include('captcha.urls')),
    # re_path('active/(?P<active_code>.*)/',
    #         ActiveUserView.as_view(), name='user_active'),
    # path('change_password/', change_password.as_view(), name='change_password'),
    # re_path('reset/(?P<active_code>.*)/',
    #         ResetView.as_view(), name='reset_pwd'),
    # path('modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),

    # path("course/", include('course.urls', namespace="course")),
    # path("users/", include('users.urls', namespace="users")),
    path("course/", include('course.urls' )),
    path("users/", include('users.urls')),
]

handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

users/urls.py
from django.urls import path
# from .views import UserinfoView, UploadImageView, UpdatePwdView, SendEmailCodeView
# from .views import UpdateEmailView, MyCourseView
from . import views
from .views import MyCourseView, UploadImageView

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    # path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('image/avatar/', UploadImageView.as_view(), name='image_upload'),
    path('change_password/', views.change_password, name='change_password'),
    #我的课程
    path("mycourse/", MyCourseView.as_view(),name='mycourse'),
]

templates/base.html
{#templates/base.html#}

{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"> -->
    <title>{% block title %}JZMJ{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}"/>
    {% block custom_css %}

    {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>

<section class="headerwrap ">
    <header>
        <div class=" header">
            <div class="top">
                <div class="wp">
<!-- {#                    <div class="fl"><p>服务电话：<b>33333333</b></p></div>#} -->
                    <!--登录后跳转-->

                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr"
                                                            src="{% static "images/top_down.png" %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                                    <dd>
                                        <h2>{{ request.user.nickname }}</h2>
                                        <p>{{ request.user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:profile' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'users:logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'users:signup' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
                    {% endif %}


                </div>
            </div>

            <div class="middle">
                <div class="wp">
                    <a href="/"><img widht="365" height="115" class="fl" src="{% static 'images/logo.PNG' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                课程
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">课程</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li {% if request.path == '/' %}class="active" {% endif %}><a
                                    href="{% url 'index' %}">首页</a></li>
                            <li {% if request.path|slice:'7' == '/course' %}class="active"{% endif %}>
                                <a href="{% url 'course:course_list' %}">
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>
</section>
<!--crumbs start-->

{#面包屑#}
{% block custom_bread %}
{% endblock %}

{#正文#}
{% block content %}
{% endblock %}


<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>
<!-- <script src="{% static 'js/header.js' %}"></script> -->

{% block custom_js %}

{% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}首页{% endblock %}

{% block custom_bread %}
{% endblock %}

{% block content %}
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="{% static 'images/feature1.png' %}"/>
					<p class="center">员工专用</p>
				</li>
				<li class="feature2">
					<img class="pic" src="{% static 'images/feature2.png' %}"/>
					<p class="center">课程最新</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="300" height="300" src="{% static 'images/module1_2.jpg' %}"/>
						<a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
					</div>
					<div class="right group_list">
                            {% for course in courses %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="250" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2 title="课程">{{ course.name }}</h2>
                                    </a>
                                </div>
                            </div>
                            {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block custom_js %}
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

templates/left_nav.html
<div class="ui secondary vertical pointing menu">
    <a id="id_profile" class="link item" href="{% url 'users:profile' %}">
        <i class="grey user icon"></i>
        <span class="v-nav-title">个人资料</span>
    </a>
    <a id="id_password" class="link item" href="{% url 'users:change_password' %}">
        <i class="grey edit icon"></i>
        <span class="v-nav-title">修改密码</span>
    </a>
</div>

templates/login.html
{% load static %}<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>登录</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/semantic.custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style1.css' %}">
</head>
<body id="v-account-body">
<div class="ui middle aligned center aligned grid">
    <div class="column v-account">
        <h2 class="ui teal image header">
            <img src="{% static 'images/logo.png' %}" class="image">
            <div class="content">
                登录账户
            </div>
        </h2>
        <form class="ui large form" novalidate method="post" action="{% url 'users:login' %}"
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="ui stacked segment">
                <div class="field">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        {{form.username}}
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        {{form.password}}
                    </div>
                </div>
                <input type="hidden" name="next" value="{{ next }}"/>
                <button class="ui fluid large teal submit button" type="submit">登录</button>
            </div>

            {% include "form_errors.html" %}

        </form>

        <div class="ui message">
                还没有账号？<a href="{% url 'users:signup' %}">注册</a>
        </div>
    </div>
</div>
</body>
</html>

templates/usercenter-base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}
        个人信息
    {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/lq.datetimepick.css' %}"/>
    {% endblock %}

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
        <div class="header2 header">
            <div class="top">
                <div class="wp">
                    <!--登录后跳转-->
                    {% if request.user.is_authenticated %}
                        <div class="personal">
                        <dl class="user fr">
                            <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                            <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                        </dl>
                        <div class="userdetail">
                        <dl>
                            <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            <dd>
                                <h2>{{ request.user.nick_name }}</h2>
                                <p>{{ request.user.username }}</p>
                            </dd>
                        </dl>
                        <div class="btn">
                        <a class="personcenter fl" href="{% url 'users:profile' %}">进入个人中心</a>
                        <a class="fr" href="{% url 'users:logout' %}">退出</a>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="signup.html">注册</a>
                        <a style="color:white" class="fr loginbtn" href="login.html">登录</a>
                    {% endif %}
                    </div>
                    </div>
                    </div>

                </div>
            </div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo2.png' %}"/></a>
                    <h1>我的内容</h1>
                </div>
            </div>
        </div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
{% endblock %}

<section>
    <div class="wp list personal_list">
        <div class="left">
            <ul>
                <li {% ifequal  '/users/profile/' request.path %}
                    class="active2"
                {% endifequal %}><a href="{% url 'users:profile' %}">个人资料</a></li>
                <!-- <li {% ifequal  '/users/mycourse/' request.path %}                          -->
                <!--     class="active2"                                                         -->
                <!-- {% endifequal %}><a href="{% url 'users:mycourse' %}">我的课程</a></li> -->
            </ul>
        </div>

        {% block custom_right_content %}
        {% endblock %}
    </div>
</section>
<!--header start-->

<div class="dialog" id="jsDialog">
    <div class="resetpwdbox dialogbox" id="jsResetDialog">
        <h1>修改密码</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <div class="cont">
            <form id="jsResetPwdForm" autocomplete="off">
                <div class="box">
                    <span class="word2">新&nbsp;&nbsp;密&nbsp;&nbsp;码</span>
                    <input type="password" id="pwd" name="password1" placeholder="6-20位非中文字符"/>
                </div>
                <div class="box">
                    <span class="word2">确定密码</span>
                    <input type="password" id="repwd" name="password2" placeholder="6-20位非中文字符"/>
                </div>
                <div class="error btns" id="jsResetPwdTips"></div>
                <div class="button">
                    <input id="jsResetPwdBtn" type="button" value="提交"/>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </div>
    <div class="dialogbox changeemai1 changephone" id="jsChangeEmailDialog">
        <h1>修改邮箱</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <p>请输入新的邮箱地址</p>
        <form id="jsChangeEmailForm" autocomplete="off">
            <div class="box">
                <input class="fl change_email" name="email" id="jsChangeEmail" type="text" placeholder="输入重新绑定的邮箱地址">
            </div>
            <div class="box">
                <input class="fl email_code" type="text" id="jsChangeEmailCode" name="code" placeholder="输入邮箱验证码">
                <input class="getcode getting" type="button" id="jsChangeEmailCodeBtn" value="获取验证码">
            </div>
            <div class="error btns change_email_tips" id="jsChangeEmailTips">请输入...</div>
            <div class="button">
                <input class="changeemai_btn" id="jsChangeEmailBtn" type="button" value="完成"/>
            </div>
            {% csrf_token %}
        </form>
    </div>

    <div class="noactivebox dialogbox" id="jsUnactiveForm">
        <h1>邮件验证提示</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <div class="center">
            <img src="{% static 'images/send.png' %}"/>
            <p>我们已经向您的邮箱<span class="green" id="jsEmailToActive">12@13.com</span>发送了邮件，<br/>为保证您的账号安全，请及时验证邮箱</p>
            <p class="a"><a class="btn" id="jsGoToEmail" target="_blank" href="http://mail.qq.com">去邮箱验证</a></p>
            <p class="zy_success upmove"></p>
            <p style="display: none;" class="sendE2">没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件（<span class="c5c">60s</span>）</p>
            <p class="sendE">没收到，您可以查看您的垃圾邮件和被过滤邮件，<br/>也可以<span class="c5c green" id="jsSenEmailAgin"
                                                                 style="cursor: pointer;">再次发送验证邮件</span></p>
        </div>
    </div>
    <div class="resetpassbox dialogbox" id="jsSetNewPwd">
        <h1>重新设置密码</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <p class="green">请输入新密码</p>
        <form id="jsSetNewPwdForm">
            <div class="box">
                <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>
                <input type="password" name="password" id="jsResetPwd" placeholder="请输入新密码"/>
            </div>
            <div class="box">
                <span class="word2">确&nbsp;认&nbsp;密&nbsp;码</span>
                <input type="password" name="password2" id="jsResetPwd2" placeholder="请再次输入新密码"/>
            </div>
            <div class="box">
                <span class="word2">验&nbsp;&nbsp;证&nbsp;&nbsp;码</span>
                <input type="text" name="code" id="jsResetCode" placeholder="请输入手机验证码"/>
            </div>
            <div class="error btns" id="jsSetNewPwdTips"></div>
            <div class="button">
                <input type="hidden" name="mobile" id="jsInpResetMobil"/>
                <input id="jsSetNewPwdBtn" type="button" value="提交"/>
            </div>
        </form>
    </div>
    <div class="forgetbox dialogbox">
        <h1>忘记密码</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <div class="cont">
            <form id="jsFindPwdForm" autocomplete="off">
                <div class="box">
                    <span class="word2">账&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号</span>
                    <input type="text" id="account" name="account" placeholder="手机/邮箱"/>
                </div>
                <div class="box">
                    <span class="word3">验证码</span>
                    <input autocomplete="off" class="form-control-captcha find-password-captcha"
                           id="find-password-captcha_1" name="captcha_f_1" placeholder="请输入验证码" type="text"/> <input
                        class="form-control-captcha find-password-captcha" id="find-password-captcha_0"
                        name="captcha_f_0" placeholder="请输入验证码" type="hidden"
                        value="5f3c00e47fb1be12d2fd15b9a860711597721b3f"/> &nbsp;<img
                        src="/captcha/image/5f3c00e47fb1be12d2fd15b9a860711597721b3f/" alt="captcha" class="captcha"/>
                </div>
                <div class="error btns" id="jsForgetTips"></div><!--忘记密码错误-->
                <div class="button">
                    <input type="hidden" name="sms_type" value="1">
                    <input id="jsFindPwdBtn" type="button" value="提交"/>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="bg" id="dialogBg"></div>


<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>

<script src="{% static 'js/plugins/jquery.upload.js' %}" type='text/javascript'></script>
<script src="{% static 'js/validate.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-user.js' %}"></script>


{% block custom_js %}
{% endblock %}


</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load static %}
{% block title %}
    我的收藏
{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:profile' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
    {% endblock %}

{% block custom_right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li ><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li ><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for fav_course in course_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' fav_course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ fav_course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' fav_course.id %}"><h2>{{ fav_course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ fav_course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ fav_course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ fav_course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ fav_course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% load static %}
{% block title %}
    我的收藏
{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:profile' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
    {% endblock %}

{% block custom_right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li ><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in org_list %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="org-detail-homepage.html">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}


{% for user_course in user_courses %}
                    <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' user_course.course.id %}">
                                <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ user_course.course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>{{ user_course.course.name }}</h2></a>
                                <span class="fl">课时：<i class="key">{{ user_course.course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ user_course.course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ user_course.course.course_org.name }}</span>
                                <span class="star fr  notlogin" data-favid="15">{{ user_course.course.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}

templates/usercenter-info.html
{% extends 'usercenter-base.html' %}
{% block title %}
    个人信息
{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:profile' %}">个人中心</a>></li>
                <li>个人信息</li>
            </ul>
        </div>
    </section>
    {% endblock %}

{% block custom_right_content %}
    <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>个人信息</h1>
			</div>
			<div class="inforcon">
				<div class="left" style="width:242px;">
                    <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'users:image_upload' %}" target='frameFile'>
                        <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                            </span>
                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                            </span>
                        </label>
                        <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
                        {% csrf_token %}
                    </form>
                    <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                        <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                    </div>
				</div>
				<form class="perinform" id="jsEditUserForm" autocomplete="off">
					<ul class="right">
						<li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                           <input type="text" name="nick_name" id="nick_name" value="{{ request.user.nick_name }}" maxlength="10">
                            <i class="error-tips"></i>
                        </li>
						<li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                           <input type="text" id="birth_day" name="birth_day" value="{{ request.user.birthday }}" readonly="readonly"/>
                            <i class="error-tips"></i>
						</li>
						<li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"  name="gender"  value="M" {% if request.user.gender == 'M' %}checked="checked"{% endif %}>男</label>
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="F" {% if request.user.gender == 'F' %}checked="checked"{% endif %}">女</label>
						</li>
						<li class="button heibtn">
							<input type="button" id="jsEditUserBtn" value="保存">
                            <!-- <button class="ui primary button" type="submit">保存</button> -->
                        </li>
					</ul>
                    {% csrf_token %}
				</form>
			</div>
		</div>
	</div>
{% endblock %}